#Ex14 - Assembly makefile Yigal Alexander and Alex Maximov
final: asoutput.h convert.h lang.h opcode.h parse.h symbol.h asoutput.c convert.c lang.c opcode.c parse.c symbol.c main.c
	gcc -Wall -ANSI -pedantic asoutput.c convert.c lang.c opcode.c parse.c symbol.c main.c -o final